apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visor-ingress
  namespace: hanzo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vm.hanzo.ai
      secretName: visor-tls
  rules:
    - host: vm.hanzo.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visor
                port:
                  number: 19000
