---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmd
  namespace: hanzo
  labels:
    app: vmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmd
  template:
    metadata:
      labels:
        app: vmd
    spec:
      containers:
        - name: vmd
          image: ghcr.io/hanzovm/vmd:1.5.4
          ports:
            - containerPort: 4822
              protocol: TCP
          env:
            - name: GUACD_LOG_LEVEL
              value: info
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: vmd
  namespace: hanzo
  labels:
    app: vmd
spec:
  type: ClusterIP
  ports:
    - port: 4822
      targetPort: 4822
      protocol: TCP
  selector:
    app: vmd
